version: 2.1 # use CircleCI 2.1
orbs:
  aws-util: solarwindscloud/aws@0
  aws-s3: circleci/aws-s3@3.1.1

executors:
  java:
    parameters:
      tag:
        type: string
        default: 12-jdk-hotspot
    docker:
      - image: 377069709311.dkr.ecr.us-east-1.amazonaws.com/base_ci_build:<< parameters.tag >>
        aws_auth:
          aws_access_key_id: $ECR_AWS_ACCESS_KEY_ID
          aws_secret_access_key: $ECR_AWS_SECRET_ACCESS_KEY
    working_directory: ~/repo
    environment:
      PROJECT_NAME: solarwinds-apm-java
      SLACK_NOTIFY_CHANNEL: "#chubi-test"
      EMOJI: ":circle-pass:"
      GITHUB_USERNAME: lt-global-circleci

commands:
  cacheit:
    steps:
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run: ./gradlew classes
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v2-dependencies-{{ checksum "build.gradle" }}

jobs:
  test:
    executor: java
    steps:
      - checkout
      - cacheit
      - run:
          name: Execute tests
          command: ./gradlew clean test
  maven-release:
    executor: java
    steps:
      - checkout
      - cacheit
      - run:
          name: release
          command: ./gradlew clean publish
  github-release:
    executor: java
    steps:
      - checkout
      - cacheit
      - run:
          name: Configure git for release
          command: |
            git config user.name "${GITHUB_USERNAME}"
            git config user.email "${GITHUB_USERNAME}-github@solarwinds.com"
      - run:
          name: Rewrite github url for release tagging
          command: |
            git config --global url."https://${GITHUB_TOKEN}:@github.com/".insteadOf git@github.com:
      - run:
          name: build
          command: ./gradlew clean build -x test
      - run:
          name: Perform release
          command: |
            VERSION=$(unzip -p agent/build/libs/solarwinds-apm-agent.jar META-INF/MANIFEST.MF | grep Implementation-Version | awk '{ print $2 }')
            VERSION=$(echo $VERSION | sed 's/[^a-z0-9.-]//g') # remove illegal characters
            echo "Current version is $VERSION"
            
            curl -f -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${GITHUB_TOKEN}"\
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/releases \
              -d '{"tag_name":"v'"$VERSION"'", "name":"v'"$VERSION"'", "body":"New release: v'"$VERSION"'", "draft":false, "prerelease":false}'
            
            source /ci-scripts/bin/helpers.sh
            send_to_slack "A new release is ready \`$VERSION\`"
  s3-stage-upload:
    executor: java
    steps:
      - checkout
      - cacheit
      - run:
          name: install jq
          command: apt-get update && apt-get install -y --no-install-recommends jq && rm -rf /var/lib/apt/lists/*
      - run:
          name: build
          command: ./gradlew clean build -x test
      - aws-util/assume-role:
          iam-role-arn: $AWS_S3_ROLE_ARN_SSP_STAGE
          install-cli: true
      - aws-s3/copy:
          arguments: |
            --dryrun \
            --acl public-read
          from: agent/build/libs/solarwinds-apm-agent.jar
          to: s3://ssp-stage-global-agent-binaries/apm/java/$(unzip -p agent/build/libs/solarwinds-apm-agent.jar META-INF/MANIFEST.MF | grep Implementation-Version | awk '{ print $2 }' | sed 's/[^a-z0-9.-]//g')

workflows:
  build_test_release:
    jobs:
      - test:
          context:
            - AWS_CIRCLE_CI_BUILD
            - GH_LIBRATO_CI_PKG_WRITE
      - approve_me:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: main
      - github-release:
          context:
            - AWS_CIRCLE_CI_BUILD
            - GH_LIBRATO_CI_PKG_WRITE
          requires:
            - test
            - approve_me
          filters:
            branches:
              only: main
      - maven-release:
          context:
            - AWS_CIRCLE_CI_BUILD
            - GH_LIBRATO_CI_PKG_WRITE
            - sonatype
            - apm-gpg-signing
          requires:
            - test
            - approve_me
          filters:
            branches:
              only: main
      - s3-stage-upload:
          context:
            - AWS_CIRCLE_CI
            - AWS_CIRCLE_CI_BUILD
            - GH_LIBRATO_CI_PKG_WRITE
            - apm-s3-publishing
