version: 2.1 # use CircleCI 2.1

executors:
  java:
    parameters:
      tag:
        type: string
        default: 12-jdk-hotspot
    docker:
      - image: 377069709311.dkr.ecr.us-east-1.amazonaws.com/base_ci_build:<< parameters.tag >>
        aws_auth:
          aws_access_key_id: $ECR_AWS_ACCESS_KEY_ID
          aws_secret_access_key: $ECR_AWS_SECRET_ACCESS_KEY
    working_directory: ~/repo
    environment:
      PROJECT_NAME: solarwinds-apm-java
      SLACK_NOTIFY_CHANNEL: "#chubi-test"
      EMOJI: ":circle-pass:"
      GP_USERNAME: lt-global-circleci
      GP_TOKEN: $GITHUB_TOKEN

commands:
  cacheit:
    steps:
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run: ./gradlew classes
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v2-dependencies-{{ checksum "build.gradle" }}

jobs:
  test:
    executor: java
    steps:
      - checkout
      - cacheit
      - run:
          name: Execute tests
          command: ./gradlew clean test
  maven-release:
    executor: java
    environment:
      # The secrets are for publishing the build artifacts to the Maven Central.
      MAVEN_USERNAME: $SONATYPE_USERNAME
      MAVEN_PASSWORD: $SONATYPE_TOKEN
      SIGNING_KEY: $GPG_PRIVATE_KEY
      SIGNING_PASSWORD: $GPG_PRIVATE_KEY_PASSPHRASE

    steps:
      - checkout
      - cacheit
      - run:
          name: release
          command: ./gradlew clean publish

workflows:
  build_test_release:
    jobs:
      - test:
          context:
            - AWS_CIRCLE_CI_BUILD
            - GH_LIBRATO_CI_PKG_WRITE
      - maven-release:
          context:
            - AWS_CIRCLE_CI_BUILD
            - GH_LIBRATO_CI_PKG_WRITE