#!/bin/bash
#
# Copyright SolarWinds Worldwide, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

export JAVA_TOOL_OPTIONS="-javaagent:/opt/solarwinds-apm/solarwinds-apm-agent-lambda.jar ${JAVA_TOOL_OPTIONS}"

if [ -z "${OTEL_SERVICE_NAME}" ]; then
    export OTEL_SERVICE_NAME=$AWS_LAMBDA_FUNCTION_NAME;
fi

if [ -z "${OTEL_INSTRUMENTATION_AWS_LAMBDA_CORE_ENABLED}" ]; then
    export OTEL_INSTRUMENTATION_AWS_LAMBDA_CORE_ENABLED=true
fi

if [ -z "${OTEL_INSTRUMENTATION_AWS_LAMBDA_EVENTS_ENABLED}" ]; then
    export OTEL_INSTRUMENTATION_AWS_LAMBDA_EVENTS_ENABLED=true
fi

if [ -z "${OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED}" ]; then
    export OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED=false
fi

if [ -z "${OTEL_INSTRUMENTATION_AWS_SDK_ENABLED}" ]; then
    export OTEL_INSTRUMENTATION_AWS_SDK_ENABLED=true
fi

export LAMBDA_RESOURCE_ATTRIBUTES="faas.instance=$AWS_LAMBDA_LOG_STREAM_NAME";
if [ -z "${OTEL_RESOURCE_ATTRIBUTES}" ]; then
    export OTEL_RESOURCE_ATTRIBUTES=$LAMBDA_RESOURCE_ATTRIBUTES;
else
    export OTEL_RESOURCE_ATTRIBUTES="$LAMBDA_RESOURCE_ATTRIBUTES,$OTEL_RESOURCE_ATTRIBUTES";
fi

export OTEL_INSTRUMENTATION_OPENTELEMETRY_API_ENABLED=true
export OTEL_INSTRUMENTATION_OPENTELEMETRY_INSTRUMENTATION_ANNOTATIONS_ENABLED=true

export OTEL_INSTRUMENTATION_AWS_LAMBDA_FLUSH_TIMEOUT=10000
export OTEL_METRIC_EXPORT_INTERVAL=1000000000

CMD="$(echo "$@" | sed 's/-Xshare:on/-Xshare:auto/g')"
exec $CMD
