#
# © SolarWinds Worldwide, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# syntax=docker/dockerfile:1
FROM openjdk:17 AS agent
WORKDIR /app
RUN curl -sSO https://agent-binaries.global.st-ssp.solarwinds.com/apm/java/latest/solarwinds-apm-agent.jar

FROM --platform=linux/amd64 ghcr.io/open-telemetry/opentelemetry-java-instrumentation/petclinic-rest-base:latest
WORKDIR /app
COPY --from=agent /app/solarwinds-apm-agent.jar .

ENV SERVER_PORT=8080
CMD ["java", "-javaagent:solarwinds-apm-agent.jar", "-jar", "spring-petclinic-rest.jar"]
