apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: ClusterIP
  selector:
    app: benchmark-db
  ports:
    - protocol: TCP
      name: postgres
      port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: db-rc-service
spec:
  type: ClusterIP
  selector:
    app: benchmark-db-rc
  ports:
    - protocol: TCP
      name: postgres
      port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: db-un-service
spec:
  type: ClusterIP
  selector:
    app: benchmark-db-un
  ports:
    - protocol: TCP
      name: postgres
      port: 5432
