name: version
description: Get agent version
outputs:
  version:
    description: agent version
    value: ${{ steps.version.outputs.VERSION }}
runs:
  using: "composite"
  steps:
    - name: Set version
      id: version
      shell: bash
      run: |
        ./gradlew build -x test
        VERSION=$(unzip -p agent/build/libs/solarwinds-apm-agent.jar META-INF/MANIFEST.MF | grep Implementation-Version | awk '{ print $2 }')
        VERSION=$(echo $VERSION | sed 's/[^a-z0-9.-]//g') # remove illegal characters
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT