name: Reversing Lab Scan

on:
  schedule:
    - cron: '0 9 */15 * *'
  workflow_dispatch:

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
  GITHUB_USERNAME: ${{ github.actor }}

jobs:
  reversing_lab_scan_agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set agent version
        id: set_version
        uses: ./.github/actions/version

      - name: Scan Jar
        uses: reversinglabs/gh-action-rl-scanner-cloud-only@v1
        with:
          artifact-to-scan: agent/build/libs/solarwinds-apm-agent.jar
          rl-verbose: true
          rl-portal-server: solarwinds
          rl-portal-org: SolarWinds
          rl-portal-group: SaaS-Agents-SWO
          rl-package-url: apm-java/solarwinds-apm-agent@${{ steps.set_version.outputs.version }}
        env:
          RLPORTAL_ACCESS_TOKEN: ${{ secrets.RL_ACCESS_TOKEN }}

  reversing_lab_scan_sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set agent version
        id: set_version
        uses: ./.github/actions/version

      - name: Scan SDK Jar
        uses: reversinglabs/gh-action-rl-scanner-cloud-only@v1
        with:
          artifact-to-scan: solarwinds-otel-sdk/build/libs/solarwinds-otel-sdk.jar
          rl-verbose: true
          rl-portal-server: solarwinds
          rl-portal-org: SolarWinds
          rl-portal-group: SaaS-Agents-SWO
          rl-package-url: apm-java/solarwinds-otel-sdk@${{ steps.set_version.outputs.version }}
        env:
          RLPORTAL_ACCESS_TOKEN: ${{ secrets.RL_ACCESS_TOKEN }}

  reversing_lab_scan_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set agent version
        id: set_version
        uses: ./.github/actions/version

      - name: Scan Jar
        uses: reversinglabs/gh-action-rl-scanner-cloud-only@v1
        with:
          artifact-to-scan: agent-lambda/build/libs/solarwinds-apm-agent-lambda.jar
          rl-verbose: true
          rl-portal-server: solarwinds
          rl-portal-org: SolarWinds
          rl-portal-group: SaaS-Agents-SWO
          rl-package-url: apm-java/solarwinds-apm-agent-lambda@${{ steps.set_version.outputs.version }}
        env:
          RLPORTAL_ACCESS_TOKEN: ${{ secrets.RL_ACCESS_TOKEN }}