# This workflow uses the trace-build account token to access appoptics/apm-java-test-apps repository where the test
# apps lives
name: Smoke-test

on:
  workflow_dispatch:

env:
  SW_APM_DEBUG_LEVEL: trace
  AGENT_DOWNLOAD_URL: https://agent-binaries.global.st-ssp.solarwinds.com/apm/java/latest/solarwinds-apm-agent.jar

jobs:
  smoke-test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run application
        working-directory: smoke-tests
        run: |
          ./gradlew :netty-test:run
        env:
          SW_APM_COLLECTOR: apm.collector.st-ssp.solarwinds.com
          SW_APM_SERVICE_KEY: ${{ secrets.SW_APM_SERVICE_KEY_STAGE }}:chubi-test

  smoke-test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run application
        working-directory: smoke-tests
        run: |
          .\gradlew.bat :netty-test:run
        env:
          SW_APM_COLLECTOR: apm.collector.st-ssp.solarwinds.com
          SW_APM_SERVICE_KEY: ${{ secrets.SW_APM_SERVICE_KEY_STAGE }}:chubi-test
